### PR TITLE
Add note to README about running inferior-dafny under mono

### PR DESCRIPTION
**Pull request by wilcoxjay**
Addresses #1.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Thanks for that. Shouldn't we just add the relevant script to the Dafny distribution instead, though? Maybe that would be the most convenient.

**Comment by wilcoxjay** [comment]
Sounds good to me! I'll look into it.

It will still require customization to remove the ".exe" from the executable name.

Now that I think about it, why is the default executable for the CLI backend `dafny` but for the server interface `dafny-server.exe`? 

If we want to change the default to `dafny-server` then I don't think any changes to the README are required. Otherwise, perhaps just a brief note on customizing the executable.

**Comment by cpitclaudel** [comment]
> Now that I think about it, why is the default executable for the CLI backend dafny but for the server interface dafny-server.exe? 

You're right, that makes no sense (esp. because the binary on Windows is not called `dafny-server.exe` either). I'll fix that soon.

**Comment by cpitclaudel** [comment]
I've pushed a wrapper script to the Dafny repo, and updated the README :) Thanks!

**Pull request closed without merging**
